---
abstract: 'dependencies for CPAN::Reporter::Transport::Metabase'
author:
  - rurban
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bundle-CPANReporter2
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.09'
